robot:
  type: so101_follower
  port: /dev/ttyACM1
  id: so101
  use_degrees: false
  max_relative_target: 5.0
  cameras:
    handeye:
      type: opencv
      index_or_path: /dev/video0
      width: 640
      height: 480
      fps: 30
